### ISSUE TITLE
Wireframe - Application

### ISSUE THREAD

**Issue by jinhgkim** [CJ-Inc/Stash#1]
Create a wireframe for the app using Figma. Minimal effort in styling for now.

**Comment by jinhgkim** [comment]
Done in Figma. https://www.figma.com/file/lxsyjZnYmj9yqR7x7NSMi7/STASH---UI%2FUX?type=design&node-id=0-1&mode=design&t=LcQ5LG7mB1orr8so-0

**Comment by amkaypark** [comment]
ios12 GUI for extension wireframe: https://www.figma.com/file/UGinoLWUylLLWk9YijQjiT/iOS-12-GUI?type=design&node-id=0-783&mode=design&t=0Lf8MdhzgtnWA0kZ-0
