### ISSUE TITLE
Wireframe - iMessenger Extension

### ISSUE THREAD

**Issue by jinhgkim** [CJ-Inc/Stash#2]
Should be the same as https://github.com/jinhgkim/Stash/issues/1#issue-1910595706

iMessage UI Kit: https://www.figma.com/file/3g8i1MD01deWqGsH2aUPx9/iOS-15---iMessage-UI-Kit-(Community)?type=design&node-id=20-78&mode=design&t=ZHHSOuLhnKr6DO1o-0

extesion expanded view: https://www.figma.com/file/85iv9PXht5yu3K3lbts4Cx/Apple-Messages-Templates-(Community)?type=design&node-id=0-41&mode=design&t=PJ2TUEe97Nn2SR7n-0

**Comment by amkaypark** [comment]
ios12 GUI for extension wireframe: https://www.figma.com/file/UGinoLWUylLLWk9YijQjiT/iOS-12-GUI?type=design&node-id=0-783&mode=design&t=0Lf8MdhzgtnWA0kZ-0
